name: Delta Force Daily Password

on:
  schedule:
    - cron: "0 1 * * *"

  workflow_dispatch:


jobs:
  run-bot:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Install dependencies
        run: |
          pip install requests playwright
          playwright install chromium


      - name: Run bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python bot.py